version: '3'

services:
  web:
    build: .
    container_name: pizza_house_web
    ports:
      - 3001:80
    volumes:
      - ./site:/usr/share/nginx/html
    depends_on:
      - db
    networks:
      - pizza_house_net
  db:
    image: mysql:5.7
    container_name: pizza_house_db
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pizza
    platform: linux/x86_64
    networks:
      - pizza_house_net
networks:
  pizza_house_net:
    driver: bridge
